=== morteza/KnowledgeConvert/res/attack_taxonomy_schema_v1.1.1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 (http://www.altova.com) by Sean Barnum (Cigital, Inc.) -->
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by Sean Barnum (Cigital, Inc.) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Attack_Taxonomy">
		<xs:annotation>
			<xs:documentation>This structure represents a defined classification taxonomy for attacks.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Taxonomy_Node" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>These nodes form the actual content and structure of the taxonomy itself.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Node_Relationship" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>This structure describes a relationship between the current node and another node in the taxonomy.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Relationship_Type" minOccurs="0">
											<xs:annotation>
												<xs:documentation>This element describes the nature of the relationship between the current node and the related node.</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="Peer"/>
													<xs:enumeration value="ResultantFrom"/>
													<xs:enumeration value="ResultsIn"/>
													<xs:enumeration value="CanAlsoBe"/>
													<xs:enumeration value="ChildOf"/>
													<xs:enumeration value="ParentOf"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Related_Node" type="xs:integer">
											<xs:annotation>
												<xs:documentation>This element is a reference to the related node in the taxonomy by ID.</xs:documentation>
											</xs:annotation>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="Type" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="Attack_Category"/>
									<xs:enumeration value="Attack_Pattern"/>
									<xs:enumeration value="Metadata_Field"/>
									<xs:enumeration value="Node_Alias"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="Pattern_Abstraction" use="optional">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="Meta"/>
									<xs:enumeration value="Standard"/>
									<xs:enumeration value="Detailed"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="Name" type="xs:string" use="required"/>
						<xs:attribute name="CAPEC_ID" type="xs:integer"/>
						<xs:attribute name="Node_ID" type="xs:integer" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Taxonomy_Name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== morteza/KnowledgeConvert/res/attack_taxonomy_v1.3.2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Attack_Taxonomy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Taxonomy_Name="CAPEC" xsi:noNamespaceSchemaLocation="http://capec.mitre.org/data/xsd/attack_taxonomy_schema_v1.1.1.xsd">
	<Taxonomy_Node Type="Attack_Category" Node_ID="1" CAPEC_ID="-1" Name="Abuse of Functionality">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>0</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="113" Pattern_Abstraction="Meta" Node_ID="2" Type="Attack_Pattern" Name="API Abuse/Misuse">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>1</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="121" Pattern_Abstraction="Standard" Node_ID="3" Type="Attack_Pattern" Name="Locate and Exploit Test APIs">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>2</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="36" Pattern_Abstraction="Detailed" Node_ID="4" Type="Attack_Pattern" Name="Using Unpublished Web Service APIs">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>2</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="160" Pattern_Abstraction="Detailed" Node_ID="5" Type="Attack_Pattern" Name="Programming to included script-based APIs">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>2</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="179" Pattern_Abstraction="Detailed" Node_ID="6" Type="Attack_Pattern" Name="Discovering, querying, and finally calling micro-services, such as w/ AJAX">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>2</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="-1" Pattern_Abstraction="Detailed" Node_ID="7" Type="Attack_Pattern" Name="Leveraging web tools (e.g. Mozilla&apos;s GreaseMonkey, Firebug) to change application behavior">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>2</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node Type="Attack_Category" Node_ID="8" CAPEC_ID="-1" Name="Functionality Misuse">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>1</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="2" Pattern_Abstraction="Standard" Node_ID="9" Type="Attack_Pattern" Name="Inducing Account Lockout">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>8</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="50" Pattern_Abstraction="Standard" Node_ID="10" Type="Attack_Pattern" Name="Password Recovery Exploitation">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>8</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="162" Pattern_Abstraction="Standard" Node_ID="11" Type="Attack_Pattern" Name="Manipulating hidden fields to change the normal flow of transactions (eShoplifting)">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>8</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="87" Pattern_Abstraction="Standard" Node_ID="12" Type="Attack_Pattern" Name="Forceful Browsing">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>1</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="143" Pattern_Abstraction="Standard" Node_ID="13" Type="Attack_Pattern" Name="Detect Unpublicized Web Pages">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>12</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="144" Pattern_Abstraction="Standard" Node_ID="14" Type="Attack_Pattern" Name="Detect Unpublicized Web Services">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>12</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="-1" Pattern_Abstraction="Standard" Node_ID="15" Type="Attack_Pattern" Name="Directory Traversal">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>1</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="95" Pattern_Abstraction="Detailed" Node_ID="16" Type="Attack_Pattern" Name="WSDL Scanning">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>1</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="48" Pattern_Abstraction="Detailed" Node_ID="17" Type="Attack_Pattern" Name="Passing Local Filenames to Functions That Expect a URL">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>1</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="54" Pattern_Abstraction="Standard" Node_ID="18" Type="Attack_Pattern" Name="Probing an Application by Targeting its Error Reporting">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>1</Related_Node>
		</Node_Relationship>
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>176</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="-1" Pattern_Abstraction="Detailed" Node_ID="19" Type="Attack_Pattern" Name="Fuzzing for garnering J2EE/.NET-based stack traces, for application mapping">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>18</Related_Node>
		</Node_Relationship>
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>184</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="-1" Pattern_Abstraction="Detailed" Node_ID="20" Type="Attack_Pattern" Name="Fuzzing and observing application log data/errors for application mapping">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>18</Related_Node>
		</Node_Relationship>
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>184</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="133" Pattern_Abstraction="Standard" Node_ID="21" Type="Attack_Pattern" Name="Try All Common Application Switches and Options">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>1</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="141" Pattern_Abstraction="Standard" Node_ID="22" Type="Attack_Pattern" Name="Cache Poisoning">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>1</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="-1" Pattern_Abstraction="Standard" Node_ID="23" Type="Attack_Category" Name="Abuse of Communication Channels">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>1</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="12" Pattern_Abstraction="Standard" Node_ID="24" Type="Attack_Pattern" Name="Choosing a Message/Channel Identifier on a Public/Multicast Channel">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>23</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="-1" Pattern_Abstraction="Detailed" Node_ID="25" Type="Attack_Pattern" Name="Exploiting Incorrectly Configured SSL Security Levels">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>23</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="156" Pattern_Abstraction="Meta" Node_ID="26" Type="Attack_Pattern" Name="Spoofing">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>0</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="148" Pattern_Abstraction="Meta" Node_ID="27" Type="Attack_Pattern" Name="Content Spoofing">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>26</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="38" Pattern_Abstraction="Standard" Node_ID="28" Type="Attack_Pattern" Name="Leveraging/Manipulating Configuration File Search Paths">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>27</Related_Node>
		</Node_Relationship>
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>220</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="194" Pattern_Abstraction="Standard" Node_ID="29" Type="Attack_Pattern" Name="Fake the Source of Data">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>27</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="145" Pattern_Abstraction="Standard" Node_ID="30" Type="Attack_Pattern" Name="Checksum Spoofing">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>27</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
	<Taxonomy_Node CAPEC_ID="-1" Pattern_Abstraction="Detailed" Node_ID="31" Type="Attack_Pattern" Name="Spoofing of UDDI/ebXML Messages">
		<Node_Relationship>
			<Relationship_Type>ChildOf</Relationship_Type>
			<Related_Node>27</Related_Node>
		</Node_Relationship>
	</Taxonomy_Node>
